version: '3'
services:
  webserver:
    build: .
    container_name: exercism
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/exercism
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal